FROM python:latest

WORKDIR /app

COPY key.txt ./key.txt
COPY services/users/ /app/

RUN pip install flask
RUN pip install requests
ENV FLASK_APP=app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]